# Generated by Django 2.1.5 on 2019-01-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formularioEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=15)),
                ('endereço', models.CharField(max_length=40)),
                ('telefone_comercial', models.CharField(max_length=15)),
                ('email_comercial', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='formularioFuncionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
